"""Branded PDF rendering for reports (reportlab).

Produces a professional letterhead document (logo, company legal details,
report table, totals, signature block, page numbering). The bytes returned here
are unsigned; cryptographic signing is applied separately in ``pdf_signing``.
"""

from __future__ import annotations

import base64
from dataclasses import dataclass, field
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.styles import ParagraphStyle

_MARGIN = 16 * mm


@dataclass
class Column:
    label: str
    align: str = "left"  # "left" | "right"
    width: float | None = None  # relative weight


@dataclass
class ReportDoc:
    title: str
    subtitle: str = ""
    meta: list[tuple[str, str]] = field(default_factory=list)
    columns: list[Column] = field(default_factory=list)
    rows: list[list[str]] = field(default_factory=list)
    indents: list[int] | None = None  # per-row indent (statements)
    bold_rows: set[int] | None = None  # row indices rendered bold (totals)
    total_label: str | None = None
    total_value: str | None = None
    footnote: str | None = None


def _hex(value: str, fallback: str = "#416180") -> colors.Color:
    try:
        return colors.HexColor(value if value.startswith("#") else f"#{value}")
    except Exception:
        return colors.HexColor(fallback)


def _logo_reader(data_url: str) -> ImageReader | None:
    if not data_url or "base64," not in data_url:
        return None
    try:
        raw = base64.b64decode(data_url.split("base64,", 1)[1])
        return ImageReader(BytesIO(raw))
    except Exception:
        return None


class _NumberedCanvas(canvas.Canvas):
    """Two-pass canvas so the footer can print 'Page X of Y'."""

    profile: dict = {}
    accent = colors.HexColor("#416180")
    signed_line = ""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_states: list[dict] = []

    def showPage(self):
        self._saved_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved_states)
        for state in self._saved_states:
            self.__dict__.update(state)
            self._draw_footer(total)
            super().showPage()
        super().save()

    def _draw_footer(self, total: int):
        w, _ = A4
        self.setStrokeColor(colors.HexColor("#D9DEE5"))
        self.setLineWidth(0.5)
        self.line(_MARGIN, 14 * mm, w - _MARGIN, 14 * mm)
        self.setFont("Helvetica", 7)
        self.setFillColor(colors.HexColor("#8A94A2"))
        self.drawString(_MARGIN, 9.5 * mm, self.signed_line)
        self.drawCentredString(w / 2, 9.5 * mm, "Confidential — generated by EquiMed")
        self.drawRightString(
            w - _MARGIN, 9.5 * mm, f"Page {self._pageNumber} of {total}"
        )


def _draw_letterhead(c: canvas.Canvas, profile: dict, accent: colors.Color, full: bool):
    w, h = A4
    band_h = 30 * mm if full else 14 * mm
    top = h - band_h
    # Accent side rule
    c.setFillColor(accent)
    c.rect(0, top, 4 * mm, band_h, stroke=0, fill=1)

    text_x = _MARGIN
    logo = _logo_reader(profile.get("logo_data_url", "")) if full else None
    if logo:
        try:
            iw, ih = logo.getSize()
            box = 18 * mm
            scale = min(box / iw, box / ih)
            lw, lh = iw * scale, ih * scale
            c.drawImage(
                logo, _MARGIN, h - 12 * mm - lh, width=lw, height=lh,
                mask="auto", preserveAspectRatio=True,
            )
            text_x = _MARGIN + lw + 6 * mm
        except Exception:
            pass

    c.setFillColor(colors.HexColor("#1B2733"))
    c.setFont("Helvetica-Bold", 15 if full else 10)
    c.drawString(text_x, h - 12 * mm, profile.get("legal_name") or "EquiMed SA")

    if full:
        c.setFont("Helvetica", 8)
        c.setFillColor(colors.HexColor("#6B7686"))
        bits = []
        addr = ", ".join(
            p for p in [profile.get("address_line"), profile.get("city"), profile.get("country")] if p
        )
        if addr:
            bits.append(addr)
        contact = "  ·  ".join(
            p for p in [profile.get("phone"), profile.get("email"), profile.get("website")] if p
        )
        legal = "  ·  ".join(
            f"{k} {v}" for k, v in [("RC", profile.get("rc_number")), ("NIU", profile.get("niu"))] if v
        )
        y = h - 16.5 * mm
        for line in [bits[0] if bits else "", contact, legal]:
            if line:
                c.drawString(text_x, y, line)
                y -= 4 * mm
        tagline = profile.get("tagline")
        if tagline:
            c.setFont("Helvetica-Oblique", 8)
            c.setFillColor(accent)
            c.drawRightString(w - _MARGIN, h - 12 * mm, tagline)

    c.setStrokeColor(accent)
    c.setLineWidth(1.2)
    c.line(_MARGIN, top + 2 * mm, w - _MARGIN, top + 2 * mm)


def render_report_pdf(profile: dict, doc: ReportDoc) -> bytes:
    accent = _hex(profile.get("accent_color") or "#416180")
    buf = BytesIO()

    _NumberedCanvas.profile = profile
    _NumberedCanvas.accent = accent
    _NumberedCanvas.signed_line = (
        f"Digitally signed · {profile.get('legal_name') or 'EquiMed'}"
    )

    def on_first(c, _d):
        _draw_letterhead(c, profile, accent, full=True)

    def on_later(c, _d):
        _draw_letterhead(c, profile, accent, full=False)

    top_margin_first = 36 * mm
    frame = Frame(
        _MARGIN, 18 * mm, A4[0] - 2 * _MARGIN, A4[1] - top_margin_first - 18 * mm,
        id="body", leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0,
    )
    template = BaseDocTemplate(
        buf, pagesize=A4,
        leftMargin=_MARGIN, rightMargin=_MARGIN,
        topMargin=top_margin_first, bottomMargin=18 * mm,
        title=doc.title,
    )
    template.addPageTemplates(
        [PageTemplate(id="main", frames=[frame], onPage=on_first)]
    )

    styles = _styles(accent)
    story: list = []
    story.append(Paragraph(doc.title, styles["title"]))
    if doc.subtitle:
        story.append(Paragraph(doc.subtitle, styles["subtitle"]))
    if doc.meta:
        meta_txt = "&nbsp;&nbsp;·&nbsp;&nbsp;".join(
            f"<b>{k}:</b> {v}" for k, v in doc.meta
        )
        story.append(Spacer(1, 3 * mm))
        story.append(Paragraph(meta_txt, styles["meta"]))
    story.append(Spacer(1, 6 * mm))

    if doc.columns:
        story.append(_data_table(doc, accent, styles))

    story.append(Spacer(1, 10 * mm))
    story.append(_signature_block(profile, styles))
    if doc.footnote:
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph(doc.footnote, styles["footnote"]))

    # Full letterhead on page 1, slim header on later pages.
    def on_any(c, d):
        (on_first if d.page == 1 else on_later)(c, d)

    template.pageTemplates[0].onPage = on_any

    template.build(story, canvasmaker=_NumberedCanvas)
    return buf.getvalue()


def _styles(accent: colors.Color) -> dict:
    return {
        "title": ParagraphStyle(
            "title", fontName="Helvetica-Bold", fontSize=17, leading=20,
            textColor=colors.HexColor("#1B2733"),
        ),
        "subtitle": ParagraphStyle(
            "subtitle", fontName="Helvetica", fontSize=9.5, leading=13,
            textColor=colors.HexColor("#6B7686"), spaceBefore=2,
        ),
        "meta": ParagraphStyle(
            "meta", fontName="Helvetica", fontSize=8.5, leading=12,
            textColor=colors.HexColor("#42505F"),
        ),
        "cell": ParagraphStyle("cell", fontName="Helvetica", fontSize=9, leading=12),
        "cellR": ParagraphStyle(
            "cellR", fontName="Helvetica", fontSize=9, leading=12, alignment=2
        ),
        "sig": ParagraphStyle(
            "sig", fontName="Helvetica", fontSize=8.5, leading=12,
            textColor=colors.HexColor("#42505F"),
        ),
        "footnote": ParagraphStyle(
            "footnote", fontName="Helvetica-Oblique", fontSize=7.5, leading=10,
            textColor=colors.HexColor("#8A94A2"),
        ),
    }


def _data_table(doc: ReportDoc, accent: colors.Color, styles: dict) -> Table:
    header = [
        Paragraph(f"<b>{c.label}</b>", _th_style(c.align)) for c in doc.columns
    ]
    body = [header]
    bold_rows = doc.bold_rows or set()
    for ridx, row in enumerate(doc.rows):
        cells = []
        for cidx, col in enumerate(doc.columns):
            raw = row[cidx] if cidx < len(row) else ""
            indent = 0
            if cidx == 0 and doc.indents and ridx < len(doc.indents):
                indent = doc.indents[ridx]
            txt = ("&nbsp;" * (indent * 3)) + _esc(raw)
            if ridx in bold_rows:
                txt = f"<b>{txt}</b>"
            style = styles["cellR"] if col.align == "right" else styles["cell"]
            cells.append(Paragraph(txt, style))
        body.append(cells)

    ts = [
        ("BACKGROUND", (0, 0), (-1, 0), accent),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("TOPPADDING", (0, 0), (-1, 0), 6),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
        ("TOPPADDING", (0, 1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("LINEBELOW", (0, 1), (-1, -1), 0.4, colors.HexColor("#E4E8ED")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F6F8FA")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]
    if doc.total_label is not None:
        total_row = [""] * len(doc.columns)
        total_row[0] = doc.total_label
        total_row[-1] = doc.total_value or ""
        body.append(
            [
                Paragraph(
                    f"<b>{_esc(total_row[i])}</b>",
                    styles["cellR"] if doc.columns[i].align == "right" else styles["cell"],
                )
                for i in range(len(doc.columns))
            ]
        )
        last = len(body) - 1
        ts += [
            ("BACKGROUND", (0, last), (-1, last), colors.HexColor("#EAEEF3")),
            ("LINEABOVE", (0, last), (-1, last), 1, accent),
            ("TOPPADDING", (0, last), (-1, last), 7),
            ("BOTTOMPADDING", (0, last), (-1, last), 7),
        ]

    total_w = A4[0] - 2 * _MARGIN
    weights = [c.width or (2.4 if i == 0 else 1) for i, c in enumerate(doc.columns)]
    wsum = sum(weights)
    col_widths = [total_w * (wt / wsum) for wt in weights]

    table = Table(body, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle(ts))
    return table


def _signature_block(profile: dict, styles: dict) -> Table:
    name = profile.get("signatory_name") or ""
    title = profile.get("signatory_title") or "Authorized Signatory"
    left = Paragraph(
        "<b>Authentication</b><br/>This document carries an embedded digital "
        "signature (PAdES). Any modification after signing invalidates it.",
        styles["sig"],
    )
    sig_name = f"<br/><b>{_esc(name)}</b>" if name else ""
    right = Paragraph(
        f"Authorized signature<br/><br/>"
        f"________________________________{sig_name}<br/>{_esc(title)}",
        styles["sig"],
    )
    t = Table([[left, right]], colWidths=[(A4[0] - 2 * _MARGIN) * 0.55, (A4[0] - 2 * _MARGIN) * 0.45])
    t.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    return t


def _th_style(align: str) -> ParagraphStyle:
    return ParagraphStyle(
        "th", fontName="Helvetica-Bold", fontSize=8, leading=11,
        textColor=colors.white, alignment=2 if align == "right" else 0,
    )


def _esc(s: str) -> str:
    return (
        str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    )
